
LOG: ====================================

LOG: Benchmarking HyCC

LOG: ====================================

LOG: TEST: gauss
LOG: SELECTION_SCHEME: yaohybrid
LOG: MINIMIZATION_TIME: 9
LOG: ARGUMENTS: ['--all-variants']

LOG: ====================================

LOG: RERUN: 0

LOG: Error: Process returned with status code 134
LOG: Error message: terminate called after throwing an instance of 'std::out_of_range'   what():  _Map_base::at Command terminated by signal 6 1.10 seconds 186272 kB Command exited with non-zero status 134 1.10 seconds 186272 kB 
LOG: retry: 0

LOG: ====================================

LOG: RERUN: 0

LOG: Error: Process returned with status code 134
LOG: Error message: terminate called after throwing an instance of 'std::out_of_range'   what():  _Map_base::at Command terminated by signal 6 1.24 seconds 186224 kB Command exited with non-zero status 134 1.24 seconds 186224 kB 
LOG: retry: 1

LOG: ====================================

LOG: RERUN: 0

LOG: Error: Process returned with status code 134
LOG: Error message: terminate called after throwing an instance of 'std::out_of_range'   what():  _Map_base::at Command terminated by signal 6 1.02 seconds 186480 kB Command exited with non-zero status 134 1.03 seconds 186480 kB 
LOG: retry: 2

LOG: ====================================

LOG: RERUN: 0

LOG: Error: Process returned with status code 134
LOG: Error message: terminate called after throwing an instance of 'std::out_of_range'   what():  _Map_base::at Command terminated by signal 6 0.95 seconds 186456 kB Command exited with non-zero status 134 0.95 seconds 186456 kB 
LOG: retry: 3

LOG: ====================================

LOG: RERUN: 0

LOG: Error: Process returned with status code 134
LOG: Error message: terminate called after throwing an instance of 'std::out_of_range'   what():  _Map_base::at Command terminated by signal 6 0.95 seconds 186248 kB Command exited with non-zero status 134 0.95 seconds 186248 kB 
LOG: retry: 4
LOG: Failed yaohybrid with args: --all-variants, exception: 
